run:
  timeout: 5m

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - forcetypeassert
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
