name: '[Blocking] Generate docs website to GitHub Pages'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-docs.yaml'
      - 'website/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-docs.yaml'
      - 'website/**'

permissions:
  contents: read

jobs:
  deploy:
    name: Generate docs website to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411
        with:
          egress-policy: audit

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" > $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - run: yarn install --frozen-lockfile
      - name: Build Website
        run: yarn build
        env:
          ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

      # deploy only after PR is merged to main
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'project-copacetic/copacetic'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          destination_dir: ./website
